name:                leia-fun
version:             0.1.0.0
github:              "jeroenvanmaanen/leia-fun"
license:             LGPL-3
author:              "Jeroen van Maanen"
maintainer:          "jeroen@leialearns.org"
copyright:           "2019 Jeroen van Maanen"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            App category here

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jeroenvanmaanen/leia-fun#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  default-extensions:
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveGeneric
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - TypeOperators
  - UndecidableInstances
  dependencies:
  - stm
  - random
  - logging-facade
  - caster
  - reflection
  - fused-effects

executables:
  leia-fun-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    default-extensions:
    - DeriveAnyClass
    - DeriveFunctor
    - DeriveGeneric
    - DerivingStrategies
    - FlexibleContexts
    - FlexibleInstances
    - GeneralizedNewtypeDeriving
    - MultiParamTypeClasses
    - TypeOperators
    - UndecidableInstances
    dependencies:
    - leia-fun
    - fused-effects

tests:
  leia-fun-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    default-extensions:
    - DeriveAnyClass
    - DeriveFunctor
    - DeriveGeneric
    - DerivingStrategies
    - FlexibleContexts
    - FlexibleInstances
    - GeneralizedNewtypeDeriving
    - MultiParamTypeClasses
    - TypeOperators
    - UndecidableInstances
    dependencies:
    - leia-fun
